In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from helperClasses.tennis_ball_detection_pytorch import BallDetectionPytorch
import cProfile
import snakeviz as sv
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [2]:
svo_path = '../../data/HD1080_SN35520970_11-03-24.svo'
ballDetection = BallDetectionPytorch(svo_path)

In [ ]:
ballDetection.calculate_background(svo_path, 'left', 100, 30)
ballDetection.save_background('left')

In [3]:
ballDetection.load_background('left')

tensor([[[ 73.,  99., 122.],
         [ 73.,  99., 122.],
         [ 73., 100., 122.],
         ...,
         [146., 156., 157.],
         [145., 156., 156.],
         [145., 157., 157.]],

        [[ 72.,  99., 123.],
         [ 72.,  99., 122.],
         [ 70.,  98., 122.],
         ...,
         [145., 155., 155.],
         [145., 155., 156.],
         [144., 156., 156.]],

        [[ 72., 100., 123.],
         [ 72.,  99., 122.],
         [ 71.,  98., 121.],
         ...,
         [143., 154., 155.],
         [143., 154., 155.],
         [143., 154., 155.]],

        ...,

        [[125., 128., 103.],
         [124., 128., 103.],
         [124., 127., 102.],
         ...,
         [156., 153., 132.],
         [156., 152., 132.],
         [156., 152., 132.]],

        [[124., 127., 102.],
         [123., 127., 102.],
         [123., 126., 101.],
         ...,
         [157., 153., 133.],
         [156., 153., 132.],
         [156., 153., 132.]],

        [[122., 126., 101.],
       

In [4]:
result_left = ballDetection.get_ball_by_frame(500, 1400, 'left', return_video=True)

100%|██████████| 900/900 [01:06<00:00, 13.57it/s]


In [ ]:
#Tensor to numpy
result_left = result_left.cpu().numpy()

In [ ]:
result_left[60]

In [ ]:
plt.hist2d(numpyresult[:,1], numpyresult[:,0], bins=25)
plt.xlim(100, 1820)
plt.ylim(100, 980)
plt.colorbar()
plt.show()

## Profiling

In [4]:
%load_ext snakeviz

In [5]:
#svo_path = '../../data/HD1080_SN35520970_11-03-24.svo'
#ballDetection = BallDetectionPytorch(svo_path)

#%snakeviz ballDetection.get_ball_by_frame(500, 1100, 'left', True)
%snakeviz ballDetection.calculate_background(svo_path, 'right', 100, 30)

100%|██████████| 3000/3000 [00:00<00:00, 428237.82it/s]


 
*** Profile stats marshalled to file 'C:\\Users\\denis\\AppData\\Local\\Temp\\tmposoolx4m'.
Embedding SnakeViz in this document...
<function display at 0x0000027115DAAF20>


## Versuch Ballerkennung Links

In [3]:
ballDetection.calculate_background(svo_path, 'right', 100, 30)

100%|██████████| 3000/3000 [00:54<00:00, 55.27it/s]


tensor([[[ 74., 100., 122.],
         [ 74., 101., 123.],
         [ 75., 101., 123.],
         ...,
         [143., 155., 156.],
         [144., 156., 156.],
         [144., 157., 157.]],

        [[ 76., 102., 124.],
         [ 76., 103., 124.],
         [ 77., 103., 125.],
         ...,
         [140., 153., 153.],
         [141., 153., 153.],
         [142., 153., 154.]],

        [[ 75., 103., 125.],
         [ 75., 102., 125.],
         [ 75., 103., 126.],
         ...,
         [137., 150., 152.],
         [137., 151., 153.],
         [138., 152., 153.]],

        ...,

        [[125., 127., 102.],
         [124., 126., 101.],
         [123., 125., 101.],
         ...,
         [153., 152., 132.],
         [153., 151., 132.],
         [153., 151., 132.]],

        [[124., 126., 101.],
         [123., 126., 101.],
         [122., 125., 100.],
         ...,
         [151., 150., 130.],
         [151., 150., 130.],
         [152., 150., 131.]],

        [[123., 125., 100.],
       

In [4]:
ballDetection.save_background('right')

In [3]:
ballDetection.load_background('right')

tensor([[[ 74., 100., 122.],
         [ 74., 101., 123.],
         [ 75., 101., 123.],
         ...,
         [143., 155., 156.],
         [144., 156., 156.],
         [144., 157., 157.]],

        [[ 76., 102., 124.],
         [ 76., 103., 124.],
         [ 77., 103., 125.],
         ...,
         [140., 153., 153.],
         [141., 153., 153.],
         [142., 153., 154.]],

        [[ 75., 103., 125.],
         [ 75., 102., 125.],
         [ 75., 103., 126.],
         ...,
         [137., 150., 152.],
         [137., 151., 153.],
         [138., 152., 153.]],

        ...,

        [[125., 127., 102.],
         [124., 126., 101.],
         [123., 125., 101.],
         ...,
         [153., 152., 132.],
         [153., 151., 132.],
         [153., 151., 132.]],

        [[124., 126., 101.],
         [123., 126., 101.],
         [122., 125., 100.],
         ...,
         [151., 150., 130.],
         [151., 150., 130.],
         [152., 150., 131.]],

        [[123., 125., 100.],
       

In [4]:
result_right = ballDetection.get_ball_by_frame(500, 1000, 'right', True)

100%|██████████| 500/500 [00:28<00:00, 17.49it/s]


In [ ]:
result_right = result_right.cpu().numpy()

In [ ]:
result_right[620]

In [ ]:
plt.imshow(ballDetection.median_background_r.cpu().numpy().astype(np.uint8))
plt.show()

In [3]:
left_test = [642, 1798]
right_test = [654, 1587]

In [4]:
ballDetection.triangulation(left_test, right_test)

[[1.90902917e+03 0.00000000e+00 9.68596313e+02 0.00000000e+00]
 [0.00000000e+00 1.90902917e+03 5.59385315e+02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 642]
 [1798]]
[[ 654]
 [1587]]


C:\FHNW_Programmiersachen\3_Sem\fhnw-cda2-tennis-analysis\helperClasses\tennis_ball_detection_pytorch.py:475: RuntimeWarning: invalid value encountered in divide
  point_3d = point_3d_hom[:3] / point_3d_hom[3]


array([nan, nan, nan])

In [10]:
import pyzed.sl as sl
import cv2

pt1 = [642, 1798]
pt2 = [654, 1587]
zed = sl.Camera()

init_params = sl.InitParameters()
init_params.set_from_svo_file(svo_path)
init_params.depth_mode = sl.DEPTH_MODE.ULTRA
init_params.coordinate_units = sl.UNIT.METER
init_params.depth_maximum_distance = 40
init_params.depth_minimum_distance = 1
init_params.sdk_verbose = True

zed.open(init_params)

calib_params = zed.get_camera_information().camera_configuration.calibration_parameters
intrinsics = calib_params.left_cam
K = np.array([[intrinsics.fx, 0, intrinsics.cx],
              [0, intrinsics.fy, intrinsics.cy],
              [0, 0, 1]])

R = calib_params._cam.disto

print(R)
            #[x, y, z]
#t = calib_params.T


# Erstelle Projektionsmatrizen
P1 = K @ np.hstack((np.eye(3), np.zeros((3, 1))))
#P2 = K @ np.hstack((R, t))
P2 = K@ R

print(P1)
print(P2)

pts1 = np.array([[pt1[0]], [pt1[1]]])
pts2 = np.array([[pt2[0]], [pt2[1]]])

print(pts1)
print(pts2)

point_3d_hom = cv2.triangulatePoints(projMatr1 = P1, projMatr2 = P2, projPoints1 = pts1, projPoints2 = pts2)

# Konvertiere zurück in nicht-homogene Koordinaten
point_3d = point_3d_hom[:3] / point_3d_hom[3]

zed.close()
point_3d.ravel()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 12 is different from 3)